name: Twitter Bot
on:
  schedule:
    - cron: "0 12 * * *"  # Se ejecuta a las 9AM hora Uruguay (UTC-3 -> 12 UTC)
  workflow_dispatch:  # Permite ejecutar el bot manualmente

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the bot
      env:
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      run: |
        python bot.py

    - name: Tweet success message
      if: success()
      run: echo "Tweet enviado correctamente."
